language: python
python:
    - "2.7"
    - "3.6"

install:
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - eval "$($HOME/miniconda/bin/conda shell.bash hook)"
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge  # needed for healpy package
    - conda update -q conda
    - conda info -a  # useful for debugging
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - conda activate test-environment
    - conda install -y astropy coverage coveralls ephem healpy matplotlib nose numpy pip pytz scipy
    - python setup.py sdist
    - pip install dist/*.tar.gz --verbose

script:
    # We need to run the tests from a new directory for correct coverage stats
    - cd /tmp && nosetests $TRAVIS_BUILD_DIR/tests/*.py --with-coverage --cover-package=aipy --no-path-adjustment

after_success:
    - coveralls
